base: ../globals.yaml

services:
  demo:
  wms:
    md:
      title: DOGAMI Bulletins 78, 79
      abstract: Scanned and georeferenced DOGAMI geologic maps for Clatsop County

layers:
  - name: svensen_quad
    title: Svensen Quad
    md: 
      attribution:
        title: Bulletin 74 Svensen Quad
    sources: [svensen_cache]

  - name: cathlamet_quad
    title: Cathlamet Quad
    md:
      attribution:
        title: Bulletin 79-11a Cathlamet Quad
    sources: [cathlamet_cache]

  - name: cannonbeach_quad
    title: Cannon Beach Quad
    md:
      attribution:
        title: Bulletin 74-03a Cannon Beach Quad
    sources: [cannonbeach_cache]

  - name: astoria_quad
    title: Astoria Quad
    md:
      attribution:
        title: Bulletin 74-02 Astoria Quad
    sources: [astoria_cache]

caches:
# There are no sources for these caches, 
# because we're using tile packages generated in ArcGIS Pro

  astoria_cache:
    sources: []
    grids: [GLOBAL_WEBMERCATOR]
    cache:
      type: compact
      version: 2
      # The tpkx file unpacks to "tile" so for example,
      # to unpack a file astoria_quad.tpkx into */cache/astoria
      #   docker run --rm -v ${PWD}/astoria_quad.tpkx:/tmp/package.zip -v mapproxy_cache:/cache -w /cache/astoria_quad busybox unzip /tmp/package.zip
      directory: /srv/mapproxy/cache/astoria_quad/tile

  cannonbeach_cache:
    sources: []
    grids: [GLOBAL_WEBMERCATOR]
    cache:
      type: compact
      version: 2
      # The tpkx file unpacks to "tile" so for example,
      # to unpack a file cannonbeach_quad.tpkx into */cache/cannonbeach_quad
      #   docker run --rm -v ${PWD}/cannonbeach_quad.tpkx:/tmp/package.zip -v mapproxy_cache:/cache -w /cache/cannonbeach_quad busybox unzip /tmp/package.zip
      directory: /srv/mapproxy/cache/cannonbeach_quad/tile

  cathlamet_cache:
    sources: []
    grids: [GLOBAL_WEBMERCATOR]
    cache:
      type: compact
      version: 2
      # The tpkx file unpacks to "tile" so for example,
      # to unpack a file cathlamet_quad.tpkx into */cache/cathlamet_quad
      #   docker run --rm -v ${PWD}/cathlamet_quad.tpkx:/tmp/package.zip -v mapproxy_cache:/cache -w /cache/cathlamet_quad busybox unzip /tmp/package.zip
      directory: /srv/mapproxy/cache/cathlamet_quad/tile

  svensen_cache:
    sources: []
    grids: [GLOBAL_WEBMERCATOR]
    cache:
      type: compact
      version: 2
      # The tpkx file unpacks to "tile" so for example,
      # to unpack a file cathlamet_quad.tpkx into */cache/cathlamet_quad
      #   docker run --rm -v ${PWD}/74_Bulletin_Svensen_Quad.tpkx:/tmp/package.zip -v mapproxy_cache:/cache -w /cache/svensen_quad busybox unzip /tmp/package.zip
      directory: /srv/mapproxy/cache/svensen_quad/tile

