seeds:
  seed_astoria2015:
    caches: [astoria2015_cache]
    grids: [astoria]
    # coverages: []
    levels:
      from: 9
      to: 17
    refresh_before:
      weeks: 3

cleanups:
  clean_astoria2015:
    caches: [astoria2015_cache]
    remove_before:
      days: 2000
    levels:
      from: 16

coverages:
